# Lab 2 – Tensors

In [1]:
import torch

## Create empty tensors
- Uninitialised tensors

In [13]:
# 1-D
x = torch.empty(1)
print(x)

# 1-D with two elements
x = torch.empty(2)
print(f"\n1-D tensor\n{x}\n")

# 2-D
x = torch.empty(2,3)
print(f"2-D tensor\n{x}\n")

# 3-D
x = torch.empty(2,3,1)
print("3-D tensor\n",x)


tensor([-5.4651e-33])

1-D tensor
tensor([-5.4651e-33,  3.0700e-41])

2-D tensor
tensor([[-5.4651e-33,  3.0700e-41,  8.0184e-01],
        [ 2.5593e-01,  4.0090e-01,  5.4051e-01]])

3-D tensor
 tensor([[[-5.4654e-33],
         [ 3.0700e-41],
         [ 8.0184e-01]],

        [[ 2.5593e-01],
         [ 4.0090e-01],
         [ 5.4051e-01]]])


## Initialise tensors to scalar, random values, zeros or ones

In [3]:
# 0-D tensor (just containing scalar value 3)
x = torch.tensor(3)
print(f'Scalar: {x} has shape {x.shape} and {x.ndim} dimensions\n')

# Random values in the interval [0,1]
x = torch.rand(2,3)
print(f"Random values:\n{x}")
print(x.dtype)

# Zeros
x = torch.zeros(2,3)
print(f"\nZeros:\n{x}")
print(x.dtype)

x = torch.zeros(2,3, dtype=torch.int)
print(f"\nZeros:\n{x}\n")

# Ones
x = torch.ones(2,3)
print(f"Ones:\n{x}")
print(f"Type: {x.dtype}\n")

x = torch.ones(2,3, dtype=torch.double)
print(f"Ones:\n{x}")

Scalar: 3 has shape torch.Size([]) and 0 dimensions

Random values:
tensor([[0.7556, 0.5935, 0.8090],
        [0.3229, 0.2650, 0.9964]])
torch.float32

Zeros:
tensor([[0., 0., 0.],
        [0., 0., 0.]])
torch.float32

Zeros:
tensor([[0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]])
Type: torch.float32

Ones:
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


## Construct tensor from data

In [4]:
# Change a list to a tensor
x = torch.tensor([0.5, 2.7])
print(x)

tensor([0.5000, 2.7000])


### Changing tensor data type


In [5]:
x = torch.rand(2,3) * 20
print(x)

# Change to integer
y = x.to(torch.int32)
print(y)

tensor([[15.1452, 10.7294,  2.2551],
        [17.2599,  3.5550, 11.4670]])
tensor([[15, 10,  2],
        [17,  3, 11]], dtype=torch.int32)


### Create a separate copy



In [6]:
a = torch.ones(2, 2)
b = a.clone()

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

tensor([[1., 1.],
        [1., 1.]])


## Basic tensor operations

- addition, subtraction, multiplication, division

In [7]:
x = torch.rand(2,2)
print(f"x = \n{x}\n")

y = torch.rand(2,2)
print(f"y = \n{y}\n")

z = torch.add(x,y) # same as z = x + y
print("x + y = ")
print(z)

z = torch.sub(x,y) # same as z = x - y
print("x - y = ")
print(z)

z = torch.mul(x,y) # same as z = x * y
print("x * y = ")
print(z)

z = torch.div(x,y) # same as z = x / y
print("x / y = ")
print(z)


x = 
tensor([[0.1841, 0.4034],
        [0.4371, 0.1266]])

y = 
tensor([[0.9836, 0.4346],
        [0.7967, 0.3609]])

x + y = 
tensor([[1.1678, 0.8380],
        [1.2337, 0.4875]])
x - y = 
tensor([[-0.7995, -0.0311],
        [-0.3596, -0.2343]])
x * y = 
tensor([[0.1811, 0.1753],
        [0.3482, 0.0457]])
x / y = 
tensor([[0.1872, 0.9284],
        [0.5486, 0.3508]])


### Inplace operations

- any function with a trailing underscore (e.g. ``add_``) will modify the value of the variable in question, in place

In [8]:
x = torch.rand(2,2)
print(f"x = \n{x}\n")

y = torch.rand(2,2)
print(f"y = \n{y}\n")

# Inplace operations
y.add_(x) # modify y by adding x to it
print(f"y + x = {y}")

y.sub_(x) # modify y by subtracting x from it
print(f"y - x = {y}")

y.mul_(x) # modify y by multiplying x to it
print(f"y * x = {y}")

y.div_(x) # modify y by dividing it by x
print(f"y / x = {y}")


x = 
tensor([[0.3915, 0.4482],
        [0.0377, 0.0347]])

y = 
tensor([[0.4494, 0.0103],
        [0.4901, 0.5720]])

y + x = tensor([[0.8409, 0.4585],
        [0.5278, 0.6067]])
y - x = tensor([[0.4494, 0.0103],
        [0.4901, 0.5720]])
y * x = tensor([[0.1759, 0.0046],
        [0.0185, 0.0199]])
y / x = tensor([[0.4494, 0.0103],
        [0.4901, 0.5720]])


## Accessing tensors

In [9]:
# Slicing
x = torch.rand(5,3)
print(x)

# Get all rows but only first column
print(x[:, 0])

# Get all columns but only the second row
print(x[1, :])

# Get a specific element
print(x[2,2])

# When the tensor returns only ONE element, use item() to get the actual value of that element
print(x[1,1].item())

y = torch.tensor([2.0])
print(y.item())

tensor([[0.6815, 0.1025, 0.2039],
        [0.3327, 0.9285, 0.1433],
        [0.6806, 0.0532, 0.4081],
        [0.9861, 0.9209, 0.7963],
        [0.9341, 0.1519, 0.1604]])
tensor([0.6815, 0.3327, 0.6806, 0.9861, 0.9341])
tensor([0.3327, 0.9285, 0.1433])
tensor(0.4081)
0.9285133481025696
2.0


## Tensor Shape & Dimensions
- The number of dimensions a tensor has is called its rank and the length in each dimension describes its ``shape``.
- To determine the length of each dimension, call ``.shape``
- To determine the number of dimensions it has, call ``.ndim``


In [10]:
x = torch.rand(5,3)
print(f'{x} \nhas shape {x.shape} and {x.ndim} dimensions\n')

tensor([[0.1080, 0.6738, 0.0492],
        [0.3845, 0.6624, 0.7033],
        [0.9495, 0.8875, 0.5785],
        [0.6194, 0.5714, 0.1628],
        [0.3112, 0.6534, 0.8566]]) 
has shape torch.Size([5, 3]) and 2 dimensions



## More on Shapes

- `[1,5,2,6]` has shape (4,) to indicate it has 4 elements and the missing element after the comma means it is a 1-D tensor or array (vector)
- `[[1,5,2,6], [1,2,3,1]]` has shape (2,4) to indicate it has 2 elements and each of these have 4 elements. This is a 2-D tensor or array (matrix or a list of vectors)
- `[[[1,5,2,6], [1,2,3,1]], [[5,2,1,2], [6,4,3,2]], [[7,8,5,3], [2,2,9,6]]]` has shape (3, 2, 4) to indicate it has 3 elements in the first dimension, and each of these contain 2 elements and each of these contain 4 elements. This is a 3-D tensor or array


## Operations on tensor dimensions
- A tensor dimension is akin to an array's axis. The number of dimensions is called rank.
- A scalar has rank 0, a vector has rank 1, a matrix has rank 2, a cuboid has rank 3, etc.
- Sometimes one wants to do an operation only on a particular dimension, e.g. on the rows only
- Across ``dim=X`` means we do the operation w.r.t to the dimension given and the rest of the dimensions of the tensor stays as they are
- in 2-D tensors, ``dim=0`` refers to the columns while ``dim=1`` refers to the rows


In [11]:
x = torch.tensor([[1,2,3],
                 [4,5,6]])

print(x.shape)
print(f'Summing across dim=0 (columns) gives: {torch.sum(x,dim=0)}')

print(f'Summing across dim=1 (rows) gives: {torch.sum(x,dim=1)}')


torch.Size([2, 3])
Summing across dim=0 (columns) gives: tensor([5, 7, 9])
Summing across dim=1 (rows) gives: tensor([ 6, 15])


## Reshaping tensors
- There are several ways to do this but using ``torch.reshape()`` is the most common
- Also look up ``torch.squeeze(), torch.unsqueeze()`` and ``torch.view()``


In [12]:
x = torch.rand(4,4)
print("Original:")
print(x)
print(x.shape)
print("\n")

# Reshape (flatten) to 1-D
y = x.reshape(16) # number of elements must be the same as original, error otherwise
print("Reshaped to 1-D:")
print(y)
print("\n")

# Reshape to 2-D
y = x.reshape(8,2)
print("Reshaped to 2-D:")
print(y)
print("\n")

# Could leave out one of the dimensions by specifying -1
y = x.reshape(2, -1)
print("Reshaped to 2 x Unspecified 2-D:")
print(y)
print(y.shape)
print("\n")

# Could use unsqueeze(0) to add a dimension at position 0
y = x.unsqueeze(0)
print(f'Using unsqueeze(0) to add dimension from original shape {x.shape} to {y.shape}')
print("\n")

Original:
tensor([[0.6316, 0.8483, 0.8018, 0.2559],
        [0.4009, 0.5405, 0.1192, 0.4771],
        [0.1919, 0.3969, 0.8268, 0.6883],
        [0.5670, 0.1697, 0.8391, 0.6574]])
torch.Size([4, 4])


Reshaped to 1-D:
tensor([0.6316, 0.8483, 0.8018, 0.2559, 0.4009, 0.5405, 0.1192, 0.4771, 0.1919,
        0.3969, 0.8268, 0.6883, 0.5670, 0.1697, 0.8391, 0.6574])


Reshaped to 2-D:
tensor([[0.6316, 0.8483],
        [0.8018, 0.2559],
        [0.4009, 0.5405],
        [0.1192, 0.4771],
        [0.1919, 0.3969],
        [0.8268, 0.6883],
        [0.5670, 0.1697],
        [0.8391, 0.6574]])


Reshaped to 2 x Unspecified 2-D:
tensor([[0.6316, 0.8483, 0.8018, 0.2559, 0.4009, 0.5405, 0.1192, 0.4771],
        [0.1919, 0.3969, 0.8268, 0.6883, 0.5670, 0.1697, 0.8391, 0.6574]])
torch.Size([2, 8])


Using unsqueeze(0) to add dimension from original shape torch.Size([4, 4]) to torch.Size([1, 4, 4])




## Convert between NumPy and PyTorch tensors

- Tensors can work on CPUs and GPUs
- NumPy arrays can only work on CPUs

In [14]:
import torch
import numpy as np

# Tensor to NumPy
a = torch.ones(5)
print(a)
print("\n")

b = a.numpy()
print(b)
print(type(b))
print("\n")

# b changes when a is modified because they share the same memory space!
a.add_(1)
print(a)
print(b)
print("\n")

tensor([1., 1., 1., 1., 1.])


[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]




In [15]:
import torch
import numpy as np

a = np.ones(5)
print(a)

b = torch.from_numpy(a)
print(b)

# Modifying array will modify the tensor as well
a += 2
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[3. 3. 3. 3. 3.]
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


# Exercise

In [16]:
# 1. Create a tensor of 100 equally spaced numbers from 0 to 2.
# Assign the tensor to x (Hint: use torch.linspace() )

# Print x
x = torch.linspace(0,2,steps=100)
print(x)

tensor([0.0000, 0.0202, 0.0404, 0.0606, 0.0808, 0.1010, 0.1212, 0.1414, 0.1616,
        0.1818, 0.2020, 0.2222, 0.2424, 0.2626, 0.2828, 0.3030, 0.3232, 0.3434,
        0.3636, 0.3838, 0.4040, 0.4242, 0.4444, 0.4646, 0.4848, 0.5051, 0.5253,
        0.5455, 0.5657, 0.5859, 0.6061, 0.6263, 0.6465, 0.6667, 0.6869, 0.7071,
        0.7273, 0.7475, 0.7677, 0.7879, 0.8081, 0.8283, 0.8485, 0.8687, 0.8889,
        0.9091, 0.9293, 0.9495, 0.9697, 0.9899, 1.0101, 1.0303, 1.0505, 1.0707,
        1.0909, 1.1111, 1.1313, 1.1515, 1.1717, 1.1919, 1.2121, 1.2323, 1.2525,
        1.2727, 1.2929, 1.3131, 1.3333, 1.3535, 1.3737, 1.3939, 1.4141, 1.4343,
        1.4545, 1.4747, 1.4949, 1.5152, 1.5354, 1.5556, 1.5758, 1.5960, 1.6162,
        1.6364, 1.6566, 1.6768, 1.6970, 1.7172, 1.7374, 1.7576, 1.7778, 1.7980,
        1.8182, 1.8384, 1.8586, 1.8788, 1.8990, 1.9192, 1.9394, 1.9596, 1.9798,
        2.0000])


In [21]:
# 3. Print the first 5 numbers in x.
print("First 5 :",x[:5])

# 4. Print the last 5 numbers in x
print("Last 5 :", x[-5:])

First 5 : tensor([0.0000, 0.0202, 0.0404, 0.0606, 0.0808])
Last 5 : tensor([1.9192, 1.9394, 1.9596, 1.9798, 2.0000])


In [22]:
# 5. Create another tensor of 100 random values between 0 and 1.
# Assign the tensor to y (Hint: use torch.rand() )
y = torch.rand(100)

# Print y
print(y)

tensor([0.5519, 0.2991, 0.8139, 0.0103, 0.0630, 0.7701, 0.5280, 0.0130, 0.2538,
        0.5576, 0.7241, 0.1579, 0.2911, 0.1527, 0.1678, 0.0409, 0.6709, 0.3024,
        0.9935, 0.0439, 0.7760, 0.6223, 0.3648, 0.1268, 0.3645, 0.6249, 0.3916,
        0.7049, 0.1599, 0.5189, 0.4906, 0.4600, 0.1796, 0.4364, 0.9801, 0.7932,
        0.5452, 0.9862, 0.2921, 0.7728, 0.8310, 0.7189, 0.2846, 0.4626, 0.2438,
        0.8611, 0.7563, 0.9035, 0.3033, 0.7292, 0.4967, 0.3209, 0.5279, 0.2349,
        0.4747, 0.6815, 0.2642, 0.1173, 0.1132, 0.0158, 0.5823, 0.3153, 0.2956,
        0.2485, 0.7130, 0.2845, 0.8174, 0.1997, 0.7461, 0.1904, 0.1430, 0.3024,
        0.4015, 0.6633, 0.5981, 0.5052, 0.6738, 0.3661, 0.6021, 0.3417, 0.8372,
        0.7747, 0.3696, 0.5683, 0.0084, 0.0808, 0.9182, 0.0363, 0.1874, 0.2614,
        0.7401, 0.8128, 0.9689, 0.2405, 0.6894, 0.6819, 0.3946, 0.2850, 0.7098,
        0.2422])


In [23]:
# 6. Multiply x and y, store the result in z
z = torch.mul(x,y)

# Print z
print(z)

tensor([0.0000e+00, 6.0426e-03, 3.2886e-02, 6.2392e-04, 5.0947e-03, 7.7785e-02,
        6.3996e-02, 1.8337e-03, 4.1016e-02, 1.0138e-01, 1.4628e-01, 3.5086e-02,
        7.0574e-02, 4.0093e-02, 4.7469e-02, 1.2392e-02, 2.1685e-01, 1.0384e-01,
        3.6126e-01, 1.6837e-02, 3.1353e-01, 2.6402e-01, 1.6215e-01, 5.8907e-02,
        1.7672e-01, 3.1558e-01, 2.0570e-01, 3.8447e-01, 9.0452e-02, 3.0401e-01,
        2.9733e-01, 2.8807e-01, 1.1608e-01, 2.9090e-01, 6.7318e-01, 5.6087e-01,
        3.9652e-01, 7.3716e-01, 2.2424e-01, 6.0888e-01, 6.7156e-01, 5.9543e-01,
        2.4145e-01, 4.0185e-01, 2.1669e-01, 7.8282e-01, 7.0283e-01, 8.5788e-01,
        2.9412e-01, 7.2183e-01, 5.0170e-01, 3.3060e-01, 5.5456e-01, 2.5148e-01,
        5.1780e-01, 7.5718e-01, 2.9892e-01, 1.3509e-01, 1.3269e-01, 1.8854e-02,
        7.0585e-01, 3.8857e-01, 3.7029e-01, 3.1625e-01, 9.2183e-01, 3.7355e-01,
        1.0899e+00, 2.7029e-01, 1.0250e+00, 2.6542e-01, 2.0226e-01, 4.3373e-01,
        5.8404e-01, 9.7821e-01, 8.9415e-

In [24]:
# 7. Reshape z to a tensor with 5 rows and 20 columns
# Store reshaped tensor to z2
z2 = z.reshape(5,-1)

# Print z2
print(z2, "\n z2 shape is ",z2.shape)

tensor([[0.0000e+00, 6.0426e-03, 3.2886e-02, 6.2392e-04, 5.0947e-03, 7.7785e-02,
         6.3996e-02, 1.8337e-03, 4.1016e-02, 1.0138e-01, 1.4628e-01, 3.5086e-02,
         7.0574e-02, 4.0093e-02, 4.7469e-02, 1.2392e-02, 2.1685e-01, 1.0384e-01,
         3.6126e-01, 1.6837e-02],
        [3.1353e-01, 2.6402e-01, 1.6215e-01, 5.8907e-02, 1.7672e-01, 3.1558e-01,
         2.0570e-01, 3.8447e-01, 9.0452e-02, 3.0401e-01, 2.9733e-01, 2.8807e-01,
         1.1608e-01, 2.9090e-01, 6.7318e-01, 5.6087e-01, 3.9652e-01, 7.3716e-01,
         2.2424e-01, 6.0888e-01],
        [6.7156e-01, 5.9543e-01, 2.4145e-01, 4.0185e-01, 2.1669e-01, 7.8282e-01,
         7.0283e-01, 8.5788e-01, 2.9412e-01, 7.2183e-01, 5.0170e-01, 3.3060e-01,
         5.5456e-01, 2.5148e-01, 5.1780e-01, 7.5718e-01, 2.9892e-01, 1.3509e-01,
         1.3269e-01, 1.8854e-02],
        [7.0585e-01, 3.8857e-01, 3.7029e-01, 3.1625e-01, 9.2183e-01, 3.7355e-01,
         1.0899e+00, 2.7029e-01, 1.0250e+00, 2.6542e-01, 2.0226e-01, 4.3373e-01,
       

In [25]:
# 8. Get the sum of each row in z2
print(f"Sum of each row in z2 : \n{torch.sum(z2, dim = 1)}\n")

# 9. Get the mean of each column in z3 (*correction : z2)
print(f"Sum of each column in z2 : \n{torch.sum(z2, dim = 0)}")

Sum of each row in z2 : 
tensor([ 1.3813,  6.4688,  8.9853, 12.6830, 17.7251])

Sum of each column in z2 : 
tensor([3.0441, 2.5218, 1.4191, 1.7305, 1.3347, 1.6885, 3.6577, 1.5783, 1.7838,
        1.8625, 2.4932, 2.5817, 3.1261, 2.0126, 3.4418, 3.4046, 2.7122, 2.1041,
        3.0722, 1.6743])


In [26]:
# 10. Reshape z to a 3D tensor (keep all the elements)
# Store reshaped tensor to z3
z3 = z2.unsqueeze(0)

# Print z3
print(f"z3 : {z3} \nz3 dimension : {z3.ndim}")

z3 : tensor([[[0.0000e+00, 6.0426e-03, 3.2886e-02, 6.2392e-04, 5.0947e-03,
          7.7785e-02, 6.3996e-02, 1.8337e-03, 4.1016e-02, 1.0138e-01,
          1.4628e-01, 3.5086e-02, 7.0574e-02, 4.0093e-02, 4.7469e-02,
          1.2392e-02, 2.1685e-01, 1.0384e-01, 3.6126e-01, 1.6837e-02],
         [3.1353e-01, 2.6402e-01, 1.6215e-01, 5.8907e-02, 1.7672e-01,
          3.1558e-01, 2.0570e-01, 3.8447e-01, 9.0452e-02, 3.0401e-01,
          2.9733e-01, 2.8807e-01, 1.1608e-01, 2.9090e-01, 6.7318e-01,
          5.6087e-01, 3.9652e-01, 7.3716e-01, 2.2424e-01, 6.0888e-01],
         [6.7156e-01, 5.9543e-01, 2.4145e-01, 4.0185e-01, 2.1669e-01,
          7.8282e-01, 7.0283e-01, 8.5788e-01, 2.9412e-01, 7.2183e-01,
          5.0170e-01, 3.3060e-01, 5.5456e-01, 2.5148e-01, 5.1780e-01,
          7.5718e-01, 2.9892e-01, 1.3509e-01, 1.3269e-01, 1.8854e-02],
         [7.0585e-01, 3.8857e-01, 3.7029e-01, 3.1625e-01, 9.2183e-01,
          3.7355e-01, 1.0899e+00, 2.7029e-01, 1.0250e+00, 2.6542e-01,
          2.